name: cfeccDNA_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python packages
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  
  # R package 
  - r-base=4.3
  
  # Perl
  - perl
  
  # bioinformatics tools 
  - samtools
  - bedtools
  - bwa
  - fastqc
  - multiqc
  
